TwilioParty/Models/Login.cs
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace TwilioParty.Models
{
    public class LogIn
    {
        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [HiddenInput(DisplayValue = false)]
        [Display(AutoGenerateField = false)]
        public string ReturnUrl { get; set; }
    }
}

TwilioParty/Models/Prize.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Web.Mvc;

namespace TwilioParty.Models
{
    public class Prize
    {
        public Prize()
        {
            Users = new List<User>();
        }

        [Key]
        [HiddenInput(DisplayValue = false)]
        [Display(AutoGenerateField = false)]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int PrizeId { get; set; }

        [Required]
        public string Name { get; set; }
        [Required]
        public int Quantity { get; set; }

        public ICollection<User> Users { get; set; }
    }
}

TwilioParty/Models/TwilioPartyContext.cs
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration.Conventions;

namespace TwilioParty.Models
{
    public class TwilioPartyContext : DbContext
    {
        public TwilioPartyContext() : base("TwilioPartyContext") { }

        public DbSet<Prize> Prizes { get; set; }
        public DbSet<User> Users { get; set; }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Conventions.Remove<PluralizingTableNameConvention>();
        }
    }
}

TwilioParty/Models/User.cs
using System.ComponentModel.DataAnnotations;

namespace TwilioParty.Models
{
    public class User
    {
        [Key]
        public string From { get; set; }
        public string Body { get; set; }

        public int PrizeId { get; set; }
        public virtual Prize Prize { get; set; }
    }
}

TwilioParty/Controllers/AuthController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;
using TwilioParty.Models;

namespace TwilioParty.Controllers
{
    [AllowAnonymous]
    public class AuthController : Controller
    {
        // GET: Login
        public ActionResult LogIn(string returnUrl)
        {
            var model = new LogIn
            {
                ReturnUrl = returnUrl
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult LogIn(LogIn model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }


            // this is bad and will have to go
            if (model.Email == "admin@admin.com" && model.Password == "password")
            {
                var identity = new ClaimsIdentity(new[] {
                new Claim(ClaimTypes.Name, "Marcos"),
                new Claim(ClaimTypes.Email, "mplacona@twilio.com"),
                new Claim(ClaimTypes.Country, "England")
            },
                    "ApplicationCookie");

                var ctx = Request.GetOwinContext();
                var authManager = ctx.Authentication;

                authManager.SignIn(identity);

                return Redirect(GetRedirectUrl(model.ReturnUrl));
            }

            // user authN failed
            ModelState.AddModelError("", "Invalid email or password");
            return View();
        }

        public ActionResult LogOut()
        {
            var ctx = Request.GetOwinContext();
            var authManager = ctx.Authentication;

            authManager.SignOut("ApplicationCookie");
            return RedirectToAction("index", "home");
        }

        private string GetRedirectUrl(string returnUrl)
        {
            if (string.IsNullOrEmpty(returnUrl) || !Url.IsLocalUrl(returnUrl))
            {
                return Url.Action("index", "home");
            }

            return returnUrl;
        }
    }

}

TwilioParty/Controllers/HomeController.cs
using System.Web.Mvc;

namespace TwilioParty.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        [AllowAnonymous] 
        public ActionResult WhatsUp()
        {
            return Content("Ahoy! I'm up!");
        }
    }
}

TwilioParty/Controllers/MessageController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using Twilio.TwiML;
using Twilio.TwiML.Mvc;
using TwilioParty.Models;

namespace TwilioParty.Controllers
{
    public class MessageController : TwilioController
    {
        // GET: Message
        [AllowAnonymous] 
        [HttpPost]
        public ActionResult Index(User data)
        {
            using (var db = new TwilioPartyContext())
            {
                var existingUserCount = db.Users.Count(a => a.From == data.From);
                var twiml = new TwilioResponse();
                if (existingUserCount > 0)
                {
                    return TwiML(twiml.Message("It seems you've already got a prize, but check this out for more goodies http://www.berlintechs.org/#party"));
                }
                // Get a random prize from DB
                var prize = db.Prizes.Where(q => q.Quantity > 0).OrderBy(r => Guid.NewGuid()).Take(1).First();
                if (prize != null)
                {    
                    prize.Quantity = prize.Quantity - 1;
                    db.SaveChanges();

                    var entry = new User { From = data.From, Body = data.Body, PrizeId = prize.PrizeId };
                    db.Users.Add(entry);
                    db.SaveChanges();

                    return TwiML(twiml.Message("Congratulations, you won a " + prize.Name + "! But that's not all you get, check this out http://www.berlintechs.org/#party"));
                }

                return Content("");
            }
            
        }

        [HttpGet]
        public ActionResult List()
        {
            var db = new TwilioPartyContext();
            var users = db.Users.ToList();
            ViewData.Model = users;
            return View();
        }
    }
}

TwilioParty/Controllers/PrizeController.cs
using System.Linq;
using System.Web.Mvc;
using TwilioParty.Models;

namespace TwilioParty.Controllers
{
    public class PrizeController : Controller
    {
        // GET: Prize
        public ActionResult List()
        {
            var db = new TwilioPartyContext();
            var prizes = db.Prizes.ToList();
            ViewData.Model = prizes;
            return View();
        }

        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Add([Bind(Exclude = "PrizeId")] Prize prize)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            using (var db = new TwilioPartyContext())
            {
                db.Prizes.Add(prize);
                db.SaveChanges();

                return RedirectToAction("List");
            }
        }

        public ActionResult Delete(int id)
        {
            var db = new TwilioPartyContext();
            var prize = db.Prizes.FirstOrDefault(s => s.PrizeId.Equals(id));
            if (prize != null)
            {
                db.Prizes.Remove(prize);
                db.SaveChanges();
            }

            return RedirectToAction("List");
        }
    }
}

TwilioParty/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

TwilioParty/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

TwilioParty/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<p>
    Hello @User.Identity.Name
</p>
<p>
    <a href="@Url.Action("logout", "auth")">Log Out</a>
</p>

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

TwilioParty/Views/Message/List.cshtml
@model IEnumerable<TwilioParty.Models.User>

@{
    ViewBag.Title = "Prizes Given";
}

<h2>@ViewBag.Title</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.From)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Prize.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Body)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.From)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Prize.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Body)
        </td>
    </tr>
}

</table>

TwilioParty/Views/Prize/Add.cshtml
@model TwilioParty.Models.Prize
@{
    ViewBag.Title = "New prize";
}

<h2>@ViewBag.Title</h2>

@Html.ValidationSummary(true)
@{ Html.EnableClientValidation(); }
@using (Html.BeginForm())
{
    @Html.EditorForModel()
    <br />
    <p>
        <button type="submit">Add new prize</button>
    </p>
}

TwilioParty/Views/Prize/List.cshtml
@model IEnumerable<TwilioParty.Models.Prize>

@{
    ViewBag.Title = "Prizes";
}

<h2>@ViewBag.Title</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Quantity)
        </th>
        <th>
            # of winners
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Quantity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Users.Count)
            </td>
            <td> 
            @Html.ActionLink(
                "Delete",
                "Delete",
                new { id = item.PrizeId },
                new { onclick = "return confirm('Delete the prize?');" })
            </td>
        </tr>
    }
    <tr>@Html.ActionLink("Add new prize", "Add", "Prize")</tr>
</table>

TwilioParty/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Twilio Party", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Messages", "List", "Message")</li>
                    <li>@Html.ActionLink("Prizes", "List", "Prize")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>